import type { Metadata } from "next";
import { ray } from "@/next-persian-fonts/ray";
import "./globals.css";
import Footer from "@/components/footer";
import ScrollToTop from "../components/scrollToTop";
import { Toaster } from "react-hot-toast";
import Profile from "@/components/profile";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ray.className}>
        <Toaster position="top-right" />
        <Profile />
        {children}
        <ScrollToTop />
        <Footer />
      </body>
    </html>
  );
}
